apiVersion: v1
kind: Pod
metadata:
  name: flexric
  labels:
    app.kubernetes.io/name: flexric
spec:
  containers:
  - name: flexric
    image: conformance/flexric:latest
    command: ["/entrypoint.sh"]
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    securityContext:
      privileged: true
    ports:                  
    - containerPort: 36421        
      name: ric      
      protocol: SCTP
---
apiVersion: v1
kind: Service
metadata:
  name: flexric
spec:
  ports:
  - name: ric
    port: 36421
    protocol: SCTP
    targetPort: 36421
  selector:
    app.kubernetes.io/name: flexric
  type: ClusterIP

