apiVersion: v1
kind: Pod
metadata:
  name: srsran
spec:
  containers:
  - name: srsran
    image: conformance/oran:latest
    command: ["/bin/bash"]
    args: ["-c", "envsubst < /gnb.yml.template > /gnb.yml && gnb -c /gnb.yml"]
    env:
    - name: LOCAL_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    securityContext:
      privileged: true
